# permissions for end users to edit agenticautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: agenticautoscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: agentic-autoscaler
    app.kubernetes.io/part-of: agentic-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: agenticautoscaler-editor-role
rules:
- apiGroups:
  - scaling.autoscaler.io
  resources:
  - agenticautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.autoscaler.io
  resources:
  - agenticautoscalers/status
  verbs:
  - get
