//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIProviderConfig) DeepCopyInto(out *AIProviderConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIProviderConfig.
func (in *AIProviderConfig) DeepCopy() *AIProviderConfig {
	if in == nil {
		return nil
	}
	out := new(AIProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscaler) DeepCopyInto(out *AgenticAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscaler.
func (in *AgenticAutoscaler) DeepCopy() *AgenticAutoscaler {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgenticAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscalerList) DeepCopyInto(out *AgenticAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgenticAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscalerList.
func (in *AgenticAutoscalerList) DeepCopy() *AgenticAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgenticAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscalerSpec) DeepCopyInto(out *AgenticAutoscalerSpec) {
	*out = *in
	out.Metrics = in.Metrics
	in.LogSource.DeepCopyInto(&out.LogSource)
	out.AIProvider = in.AIProvider
	out.HPACoexistence = in.HPACoexistence
	out.Observability = in.Observability
	out.Detection = in.Detection
	if in.LogPatterns != nil {
		in, out := &in.LogPatterns, &out.LogPatterns
		*out = make([]LogPatternSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscalerSpec.
func (in *AgenticAutoscalerSpec) DeepCopy() *AgenticAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgenticAutoscalerStatus) DeepCopyInto(out *AgenticAutoscalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastCleanSince != nil {
		in, out := &in.LastCleanSince, &out.LastCleanSince
		*out = (*in).DeepCopy()
	}
	if in.LogPatternWarnings != nil {
		in, out := &in.LogPatternWarnings, &out.LogPatternWarnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgenticAutoscalerStatus.
func (in *AgenticAutoscalerStatus) DeepCopy() *AgenticAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(AgenticAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionConfig) DeepCopyInto(out *DetectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionConfig.
func (in *DetectionConfig) DeepCopy() *DetectionConfig {
	if in == nil {
		return nil
	}
	out := new(DetectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPACoexistence) DeepCopyInto(out *HPACoexistence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPACoexistence.
func (in *HPACoexistence) DeepCopy() *HPACoexistence {
	if in == nil {
		return nil
	}
	out := new(HPACoexistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaConfig) DeepCopyInto(out *KafkaConfig) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaConfig.
func (in *KafkaConfig) DeepCopy() *KafkaConfig {
	if in == nil {
		return nil
	}
	out := new(KafkaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogPatternSpec) DeepCopyInto(out *LogPatternSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogPatternSpec.
func (in *LogPatternSpec) DeepCopy() *LogPatternSpec {
	if in == nil {
		return nil
	}
	out := new(LogPatternSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSourceConfig) DeepCopyInto(out *LogSourceConfig) {
	*out = *in
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(LokiConfig)
		**out = **in
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSourceConfig.
func (in *LogSourceConfig) DeepCopy() *LogSourceConfig {
	if in == nil {
		return nil
	}
	out := new(LogSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiConfig) DeepCopyInto(out *LokiConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiConfig.
func (in *LokiConfig) DeepCopy() *LokiConfig {
	if in == nil {
		return nil
	}
	out := new(LokiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricQueries) DeepCopyInto(out *MetricQueries) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricQueries.
func (in *MetricQueries) DeepCopy() *MetricQueries {
	if in == nil {
		return nil
	}
	out := new(MetricQueries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityConfig) DeepCopyInto(out *ObservabilityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityConfig.
func (in *ObservabilityConfig) DeepCopy() *ObservabilityConfig {
	if in == nil {
		return nil
	}
	out := new(ObservabilityConfig)
	in.DeepCopyInto(out)
	return out
}
